/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Personnel;
import classe_special.Confirm;
import classe_special.EventCallBack;
import classe_special.EventTextField;
import classe_special.Message;
import classe_special.ScrollBar;
import dao.PersonnelDAO;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import javax.swing.table.DefaultTableModel;
import report.ReportPersonnel;

/**
 *
 * @author HP
 */
public class PanelPersonnel extends javax.swing.JPanel {
boolean modifier;
String search;
    /**
     * Creates new form PanelPersonnel
     */
    public PanelPersonnel() {
        initComponents();
        liste_personnel();
        listeCarte();
        btnRecherche.addEvent(new EventTextField() {
            @Override
            public void onPressed(EventCallBack call) {
                vider();
        PersonnelDAO pdao = new PersonnelDAO();
        List<Personnel> personnel = pdao.recherche(btnRecherche.getText());
        String genre;
        
        for (int i = 0; i < personnel.size(); i++) {
            if(personnel.get(i).isSexe()==true)
                genre="homme";
            else
                genre="femme";
            ((DefaultTableModel) tb_personnel.getModel()).addRow(new Object[]{
                personnel.get(i).getIdp(),
                personnel.get(i).getNom(),
                personnel.get(i).getPrenom(),
                personnel.get(i).getCIN(),
                personnel.get(i).getPoste(),
                personnel.get(i).getTelephone(),
                personnel.get(i).getDate_naissance(),
                personnel.get(i).getDate_embauche(),
                genre,
                personnel.get(i).getSalaire()
                
            });
           }
          }

            @Override
            public void onCancel() {
            }

        
    });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameEnregistrer = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btnEnregistrer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        menu = new javax.swing.JPopupMenu();
        editer = new javax.swing.JMenuItem();
        supprimer = new javax.swing.JMenuItem();
        Nom = new javax.swing.JMenu();
        croissant = new javax.swing.JMenuItem();
        decroissant = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JLabel();
        btnModifier = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tb_personnel = new classe_special.Tableaux();
        jSeparator1 = new javax.swing.JSeparator();
        btnRecherche = new classe_special.TextSearch();
        carte1 = new classe_special.Carte();
        carte2 = new classe_special.Carte();
        carte3 = new classe_special.Carte();

        FrameEnregistrer.setLocation(new java.awt.Point(465, 165));
        FrameEnregistrer.setUndecorated(true);
        FrameEnregistrer.setResizable(false);
        FrameEnregistrer.setSize(new java.awt.Dimension(488, 443));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prenom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Poste");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Telephone");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Date naissance");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date embauche");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Genre");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("homme");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("femme");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Salaire");

        btnEnregistrer.setBackground(new java.awt.Color(51, 102, 255));
        btnEnregistrer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnAnnuler.setBackground(new java.awt.Color(255, 102, 102));
        btnAnnuler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout FrameEnregistrerLayout = new javax.swing.GroupLayout(FrameEnregistrer.getContentPane());
        FrameEnregistrer.getContentPane().setLayout(FrameEnregistrerLayout);
        FrameEnregistrerLayout.setHorizontalGroup(
            FrameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameEnregistrerLayout.setVerticalGroup(
            FrameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                menuPopupMenuWillBecomeVisible(evt);
            }
        });

        editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        editer.setText("Modifier");
        editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerActionPerformed(evt);
            }
        });
        menu.add(editer);

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        menu.add(supprimer);

        Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder.png"))); // NOI18N
        Nom.setText("Ordonné par Nom");

        croissant.setText("Croissante");
        croissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissantActionPerformed(evt);
            }
        });
        Nom.add(croissant);

        decroissant.setText("Decroissante");
        decroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decroissantActionPerformed(evt);
            }
        });
        Nom.add(decroissant);

        menu.add(Nom);

        setBackground(new java.awt.Color(245, 245, 245));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LISTE DES PERSONNELS");

        btnAjouter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ajouter.png"))); // NOI18N
        btnAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });

        btnModifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        btnModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });

        btnSupprimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imprimante.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupprimer)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAjouter)
                            .addComponent(btnModifier)))))
        );

        scroll.setBorder(null);
        scroll.setVerticalScrollBar(new ScrollBar());
        scroll.getVerticalScrollBar().setBackground(Color.BLUE);

        tb_personnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idp", "Nom", "Prenom", "CIN", "Poste", "Telephone", "Date Naissance", "Embauche", "Genre", "Salaire"
            }
        ));
        tb_personnel.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tb_personnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_personnelMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_personnelMouseReleased(evt);
            }
        });
        scroll.setViewportView(tb_personnel);

        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        carte1.setBackground(new java.awt.Color(51, 51, 51));

        carte2.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(carte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(carte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carte1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {carte1, carte2, carte3});

    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        PersonnelDAO pdao = new PersonnelDAO();
        String CIN=jTextField1.getText();
        String nom=jTextField2.getText();
        String prenom=jTextField3.getText();
        String poste=jTextField4.getText();
        String telephone=jTextField5.getText();
        Date date_naissance=jDateChooser1.getDate();
        Date date_embauche=jDateChooser2.getDate();
        
        boolean sexe=true;
        if(jRadioButton1.isSelected()==true)
            sexe=true;
        else if(jRadioButton2.isSelected()==true)
            sexe=false;
        String salaire=jTextField8.getText();
        if(CIN.equals("")||nom.equals("")||prenom.equals("")||poste.equals("")||telephone.equals("") ||salaire.equals("")){
            new Message().affiche("Veuillez renseigner tous les champs ",Message.INFO);
        }
        else if(modifier==false) {
            Personnel p = new Personnel(CIN, nom, prenom, poste, telephone, date_naissance, date_embauche, sexe,Double.parseDouble(salaire));
            pdao.inserer(p);
            vider();
            liste_personnel();
            FrameEnregistrer.setVisible(false);
        }
        else if(modifier==true){
            int index = tb_personnel.getSelectedRow();
             int id = (int)tb_personnel.getValueAt(index,0);
            Personnel ut = new Personnel(CIN, nom, prenom, poste, telephone, date_naissance, date_embauche, sexe,Double.parseDouble(salaire));
            pdao.modifier(ut, id);
            vider();
            liste_personnel();
            FrameEnregistrer.setVisible(false);
        }  
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        FrameEnregistrer.setVisible(false);
        vider();
            liste_personnel();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void tb_personnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_personnelMouseClicked
       int index = tb_personnel.getSelectedRow();
        if (index!=-1){
          int id = (int)tb_personnel.getValueAt(index,0);
            PersonnelDAO pdao = new PersonnelDAO();
            Personnel etu = pdao.recherche(id);
            jTextField1.setText(etu.getCIN());
            jTextField2.setText(etu.getNom());
            jTextField3.setText(etu.getPrenom());
            jTextField4.setText(etu.getPoste());
            jTextField5.setText(etu.getTelephone());
            jDateChooser1.setDate(etu.getDate_naissance());
            jDateChooser2.setDate(etu.getDate_embauche());
            boolean sexe=etu.isSexe();
            if(sexe==true)
                jRadioButton1.setSelected(true);
            else
                jRadioButton2.setSelected(true);
            jTextField8.setText(etu.getSalaire()+"");
        }
    }//GEN-LAST:event_tb_personnelMouseClicked

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked
        FrameEnregistrer.setVisible(true);
        modifier=false;
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_btnAjouterMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        int index = tb_personnel.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une ligne",Message.INFO);
        }
        else {
        FrameEnregistrer.setVisible(true);
        modifier=true;
        }
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        int index = tb_personnel.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une ligne",Message.INFO);
        }
        else {
       new Confirm().affiche("Supprimer","Etes vous sur de vouloir Supprimer!!!", new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent ae) {
             int id = (int)tb_personnel.getValueAt(index,0);
            PersonnelDAO pdao = new PersonnelDAO();
            pdao.supprimer(id);
            vider();
            liste_personnel();
               }
           });
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerActionPerformed
        FrameEnregistrer.setVisible(true);
        modifier=true;
    }//GEN-LAST:event_editerActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        int index = tb_personnel.getSelectedRow();
        new Confirm().affiche("Supprimer","Etes vous sur de vouloir Supprimer!!!", new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent ae) {
             int id = (int)tb_personnel.getValueAt(index,0);
            PersonnelDAO pdao = new PersonnelDAO();
            pdao.supprimer(id);
            vider();
            liste_personnel();
               }
           });
    }//GEN-LAST:event_supprimerActionPerformed

    private void menuPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_menuPopupMenuWillBecomeVisible

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                int index=tb_personnel.rowAtPoint(SwingUtilities.convertPoint(menu,new Point(1, 1), tb_personnel));
                if(index > -1){
                    tb_personnel.setRowSelectionInterval(index, index);
                    int id = (int)tb_personnel.getValueAt(index,0);
            PersonnelDAO pdao = new PersonnelDAO();
            Personnel etu = pdao.recherche(id);
            jTextField1.setText(etu.getCIN());
            jTextField2.setText(etu.getNom());
            jTextField3.setText(etu.getPrenom());
            jTextField4.setText(etu.getPoste());
            jTextField5.setText(etu.getTelephone());
            jDateChooser1.setDate(etu.getDate_naissance());
            jDateChooser2.setDate(etu.getDate_embauche());
            boolean sexe=etu.isSexe();
            if(sexe==true)
                jRadioButton1.setSelected(true);
            else
                jRadioButton2.setSelected(true);
            jTextField8.setText(etu.getSalaire()+"");
                }
            }
        });

    }//GEN-LAST:event_menuPopupMenuWillBecomeVisible

    private void tb_personnelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_personnelMouseReleased
        if(SwingUtilities.isRightMouseButton(evt)){
            menu.show(this,this.getMousePosition().x,this.getMousePosition().y);
        }
    }//GEN-LAST:event_tb_personnelMouseReleased

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
     new ReportPersonnel().afficher_report();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void croissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissantActionPerformed
        vider();
        PersonnelDAO pdao = new PersonnelDAO();
        List<Personnel> personnel = pdao.listeCroissante();
        String genre;
        
        for (int i = 0; i < personnel.size(); i++) {
            if(personnel.get(i).isSexe()==true)
                genre="homme";
            else
                genre="femme";
            ((DefaultTableModel) tb_personnel.getModel()).addRow(new Object[]{
                personnel.get(i).getIdp(),
                personnel.get(i).getNom(),
                personnel.get(i).getPrenom(),
                personnel.get(i).getCIN(),
                personnel.get(i).getPoste(),
                personnel.get(i).getTelephone(),
                personnel.get(i).getDate_naissance(),
                personnel.get(i).getDate_embauche(),
                genre,
                personnel.get(i).getSalaire()
                
            });
    }
    }//GEN-LAST:event_croissantActionPerformed

    private void decroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decroissantActionPerformed
        vider();
        PersonnelDAO pdao = new PersonnelDAO();
        List<Personnel> personnel = pdao.listeDecroissante();
        String genre;
        
        for (int i = 0; i < personnel.size(); i++) {
            if(personnel.get(i).isSexe()==true)
                genre="homme";
            else
                genre="femme";
            ((DefaultTableModel) tb_personnel.getModel()).addRow(new Object[]{
                personnel.get(i).getIdp(),
                personnel.get(i).getNom(),
                personnel.get(i).getPrenom(),
                personnel.get(i).getCIN(),
                personnel.get(i).getPoste(),
                personnel.get(i).getTelephone(),
                personnel.get(i).getDate_naissance(),
                personnel.get(i).getDate_embauche(),
                genre,
                personnel.get(i).getSalaire()
                
            });
    }
    }//GEN-LAST:event_decroissantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameEnregistrer;
    private javax.swing.JMenu Nom;
    private javax.swing.JLabel btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JLabel btnModifier;
    private classe_special.TextSearch btnRecherche;
    private javax.swing.JLabel btnSupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private classe_special.Carte carte1;
    private classe_special.Carte carte2;
    private classe_special.Carte carte3;
    private javax.swing.JMenuItem croissant;
    private javax.swing.JMenuItem decroissant;
    private javax.swing.JMenuItem editer;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JMenuItem supprimer;
    private classe_special.Tableaux tb_personnel;
    // End of variables declaration//GEN-END:variables
public void vider() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField8.setText("");
        DefaultTableModel model = (DefaultTableModel) tb_personnel.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
private void liste_personnel() {
        PersonnelDAO pdao = new PersonnelDAO();
        List<Personnel> personnel = pdao.liste();
        String genre;
        
        for (int i = 0; i < personnel.size(); i++) {
            if(personnel.get(i).isSexe()==true)
                genre="homme";
            else
                genre="femme";
            ((DefaultTableModel) tb_personnel.getModel()).addRow(new Object[]{
                personnel.get(i).getIdp(),
                personnel.get(i).getNom(),
                personnel.get(i).getPrenom(),
                personnel.get(i).getCIN(),
                personnel.get(i).getPoste(),
                personnel.get(i).getTelephone(),
                personnel.get(i).getDate_naissance(),
                personnel.get(i).getDate_embauche(),
                genre,
                personnel.get(i).getSalaire()
                
            });
    }
}
private void listeCarte(){
    PersonnelDAO pdao = new PersonnelDAO();
     List<Personnel> personnel = pdao.liste();
     int nbreTotal=personnel.size();
     int nbreh=0; int nbref=0;
     for (int i = 0; i < personnel.size(); i++) {
            if(personnel.get(i).isSexe()==true)
                nbreh++;
            else
                nbref++;
     }
     carte1.setData("Nombre Emplyé", ""+nbreTotal);
     carte2.setData("Nombre Homme", ""+nbreh);
     carte3.setData("Nombre Femme", ""+nbref);
  }
public void acces(){
    btnAjouter.setVisible(false);
    btnModifier.setVisible(false);
    btnSupprimer.setVisible(false);
    tb_personnel.setEnabled(false);
    menu.removeAll();
}
}
