/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Caisse;
import classe.Utilisateur;
import classe_special.Message;
import classe_special.ScrollBar;
import dao.CaisseDAO;
import dao.UtilisateurDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class PanelCaisse extends javax.swing.JPanel {
boolean modifier;
public Utilisateur user=new Utilisateur();
    /**
     * Creates new form PanelCaisse
     */
    public PanelCaisse(Utilisateur u) {
        initComponents();
        user=u;
        liste_depense();
        caisse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        frameEnregistrer = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnEnregistrer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        tout = new javax.swing.JRadioButton();
        entree = new javax.swing.JRadioButton();
        sortie = new javax.swing.JRadioButton();
        scroll = new javax.swing.JScrollPane();
        tb_caisse = new classe_special.Tableaux();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        carte1 = new classe_special.Carte();
        carte2 = new classe_special.Carte();
        carte3 = new classe_special.Carte();
        jLabel4 = new javax.swing.JLabel();

        frameEnregistrer.setLocation(new java.awt.Point(465, 165));
        frameEnregistrer.setUndecorated(true);
        frameEnregistrer.setSize(new java.awt.Dimension(417, 358));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "entrée", "sortie" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Libelle");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Montant");

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnAnnuler.setBackground(new java.awt.Color(255, 51, 51));
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 199, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameEnregistrerLayout = new javax.swing.GroupLayout(frameEnregistrer.getContentPane());
        frameEnregistrer.getContentPane().setLayout(frameEnregistrerLayout);
        frameEnregistrerLayout.setHorizontalGroup(
            frameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameEnregistrerLayout.setVerticalGroup(
            frameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("CAISSE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(268, 268, 268))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonGroup1.add(tout);
        tout.setSelected(true);
        tout.setText("TOUT");
        tout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toutActionPerformed(evt);
            }
        });

        buttonGroup1.add(entree);
        entree.setText("ENTREE");
        entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreeActionPerformed(evt);
            }
        });

        buttonGroup1.add(sortie);
        sortie.setText("SORTIE");
        sortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortieActionPerformed(evt);
            }
        });

        scroll.setBorder(null);
        scroll.setVerticalScrollBar(new ScrollBar());
        scroll.getVerticalScrollBar().setBackground(Color.BLUE);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tb_caisse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id caisse", "type", "libelle", "Montant", "Date operateur", "Utilisateur"
            }
        ));
        tb_caisse.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tb_caisse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_caisseMouseClicked(evt);
            }
        });
        scroll.setViewportView(tb_caisse);

        btnAjouter.setBackground(new java.awt.Color(102, 102, 255));
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("Enregistrer Depense");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(255, 51, 51));
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        carte1.setBackground(new java.awt.Color(51, 51, 51));

        carte2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("journal de la caisse");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(tout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(entree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63)
                        .addComponent(carte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(carte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tout)
                        .addComponent(entree)
                        .addComponent(sortie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toutActionPerformed
        vider(); liste_depense();
    }//GEN-LAST:event_toutActionPerformed

    private void entreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreeActionPerformed
        vider(); liste_entre();
    }//GEN-LAST:event_entreeActionPerformed

    private void sortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortieActionPerformed
        vider(); liste_sortie();
    }//GEN-LAST:event_sortieActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        frameEnregistrer.setVisible(true);
        modifier=false;
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        frameEnregistrer.setVisible(false);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        CaisseDAO cdao = new CaisseDAO();
        String mont = jTextField2.getText();
        String libelle =jTextField1.getText();
        String type = jComboBox1.getSelectedItem().toString();
        if (mont.equals("") || libelle.equals("")|| type.equals("")) {
            new Message().affiche("Veuillez renseigner tous les champs ",Message.ALERT);
        } 
        else if(modifier==false) {
            Caisse css = new Caisse(user.getIdu(),type, libelle,Float.parseFloat(mont));
            cdao.inserer(css);
            vider();
            liste_depense();
            montant=0;mEntre=0;mSortie=0;
            caisse();
            frameEnregistrer.setVisible(false);
        }
        else if(modifier==true) {
            int index = tb_caisse.getSelectedRow();
             int id = (int)tb_caisse.getValueAt(index,0);
            Caisse css = new Caisse(user.getIdu(),type, libelle,Float.parseFloat(mont));
            cdao.modifier(css, id);
            vider();
            liste_depense();
            montant=0;mEntre=0;mSortie=0;
            caisse();
            frameEnregistrer.setVisible(false);
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        int index = tb_caisse.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une ligne",Message.ALERT);
        }
        else {
        frameEnregistrer.setVisible(true);
        modifier=true;
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void tb_caisseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_caisseMouseClicked
        int index = tb_caisse.getSelectedRow();
        if (index!=-1){
          int id = (int)tb_caisse.getValueAt(index,0);
            CaisseDAO cdao = new CaisseDAO();
            Caisse css = cdao.recherche(id);
            jComboBox1.setSelectedItem(css.getType());
            jTextField1.setText(css.getLibelle());
            jTextField2.setText(css.getMontant()+"");
        }
    }//GEN-LAST:event_tb_caisseMouseClicked

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        int index = tb_caisse.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une ligne",Message.ALERT);
        }
        else {
        int id = (int)tb_caisse.getValueAt(index,0);
        CaisseDAO cdao = new CaisseDAO();
        cdao.supprimer(id);
        vider();
        liste_depense();
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       new FrameStat().statistiquaCaisseEntrée();
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private classe_special.Carte carte1;
    private classe_special.Carte carte2;
    private classe_special.Carte carte3;
    private javax.swing.JRadioButton entree;
    private javax.swing.JFrame frameEnregistrer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JRadioButton sortie;
    private classe_special.Tableaux tb_caisse;
    private javax.swing.JRadioButton tout;
    // End of variables declaration//GEN-END:variables
private void liste_depense() {
        CaisseDAO pdao = new CaisseDAO();
        List<Caisse> css = pdao.liste();
        
        
        for (int i = 0; i < css.size(); i++) {
            UtilisateurDAO udao=new UtilisateurDAO();
            Utilisateur ut=udao.recherche(css.get(i).getIdu());
            String login=ut.getLogin();
            ((DefaultTableModel) tb_caisse.getModel()).addRow(new Object[]{
                  css.get(i).getIdCaisse(),
                  css.get(i).getType(),
                  css.get(i).getLibelle(),
                  css.get(i).getMontant(),
                  css.get(i).getDate_operation(),
                  login
            });
            }
    }
public void vider() {
        DefaultTableModel model = (DefaultTableModel) tb_caisse.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
private void liste_entre() {
        CaisseDAO pdao = new CaisseDAO();
        List<Caisse> css = pdao.liste();
        UtilisateurDAO udao=new UtilisateurDAO();
        for (int i = 0; i < css.size(); i++) {
            Utilisateur u=udao.recherche(css.get(i).getIdu());
            if(css.get(i).getType().equals("entrée")){
            ((DefaultTableModel) tb_caisse.getModel()).addRow(new Object[]{
                  css.get(i).getIdCaisse(),
                  css.get(i).getType(),
                  css.get(i).getLibelle(),
                  css.get(i).getMontant(),
                  css.get(i).getDate_operation(),
                  u.getLogin()
            });
            }
        }
    }
private void liste_sortie() {
        CaisseDAO pdao = new CaisseDAO();
        List<Caisse> css = pdao.liste();
        UtilisateurDAO udao=new UtilisateurDAO();
        for (int i = 0; i < css.size(); i++) {
            
            Utilisateur u=udao.recherche(css.get(i).getIdu());
            if(css.get(i).getType().equals("sortie")){
            ((DefaultTableModel) tb_caisse.getModel()).addRow(new Object[]{
                  css.get(i).getIdCaisse(),
                  css.get(i).getType(),
                  css.get(i).getLibelle(),
                  css.get(i).getMontant(),
                  css.get(i).getDate_operation(),
                  u.getLogin()
            });
            }
        }
    }
public void acces(){
    btnModifier.setVisible(false);btnSupprimer.setVisible(false);
}
float montant=0;float mEntre=0;float mSortie=0;

  private void caisse(){
    CaisseDAO pdao = new CaisseDAO();
        List<Caisse> css = pdao.liste();
        for (int i = 0; i < css.size(); i++) {
            montant+=css.get(i).getMontant();
            
            if(css.get(i).getType().equals("sortie")){
            mSortie+=css.get(i).getMontant();
            }
            else if(css.get(i).getType().equals("entrée")){
                mEntre+=css.get(i).getMontant();
            }
        }
       carte1.setData("Montant Total", ""+montant); 
       carte2.setData("Montant Entrée", ""+mEntre); 
       carte3.setData("Montant Sortie", ""+mSortie); 
  }
  
}

