/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Modele;
import classe_special.Message;
import classe_special.ModelePane;
import classe_special.ScrollBar;
import classe_special.WrapLayout;
import dao.ModeleDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author fofana
 */
public class PanelModele extends javax.swing.JPanel {

    /**
     * Creates new form PanelModele
     */
    public PanelModele() {
        initComponents();
        jPanel1.setBackground(Color.WHITE);
        jPanel1.setLayout(new WrapLayout(WrapLayout.LEFT, 10, 10));
        listModele();
    }
public Modele modeselec=null;

    public void selection(ModelePane mp){
        modeselec=mp.getMode();
    }
public ModelePane mp;

public void listModele(){
    ModeleDAO m=new ModeleDAO();
    List<Modele> mod =m.liste();
    for(int i=0; i<mod.size();i++){
        mp=new ModelePane();
        mp.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                selection(mp);
            }
        });
        mp.setData(mod.get(i));
        jPanel1.add(mp);
        jPanel1.repaint();jPanel1.revalidate();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameAdd = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        buttonBorder1 = new classe_special.ButtonBorder();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textField1 = new javax.swing.JTextField();
        labelImage1 = new classe_special.LabelImage();
        buttonBorder2 = new classe_special.ButtonBorder();
        buttonBorder3 = new classe_special.ButtonBorder();
        scroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonBorder4 = new classe_special.ButtonBorder();

        FrameAdd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FrameAdd.setLocation(new java.awt.Point(234, 166));
        FrameAdd.setUndecorated(true);
        FrameAdd.setSize(new java.awt.Dimension(519, 459));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonBorder1.setText("Choisir une image");
        buttonBorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom Modele");

        jLabel3.setText("Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "Enfants" }));

        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imageVide.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBorder2.setText("Ajouter");
        buttonBorder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder2ActionPerformed(evt);
            }
        });

        buttonBorder3.setText("Annuler");
        buttonBorder3.setBorderColor(new java.awt.Color(255, 0, 0));
        buttonBorder3.setColorClick(new java.awt.Color(255, 153, 153));
        buttonBorder3.setColorOver(new java.awt.Color(255, 204, 204));
        buttonBorder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameAddLayout = new javax.swing.GroupLayout(FrameAdd.getContentPane());
        FrameAdd.getContentPane().setLayout(FrameAddLayout);
        FrameAddLayout.setHorizontalGroup(
            FrameAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FrameAddLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(buttonBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(buttonBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        FrameAddLayout.setVerticalGroup(
            FrameAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAddLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        scroll.setBorder(null);
        scroll.setVerticalScrollBar(new ScrollBar());
        scroll.getVerticalScrollBar().setBackground(Color.BLUE);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        scroll.setViewportView(jPanel1);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel Modele");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        buttonBorder4.setText("Ajouter");
        buttonBorder4.setBorderColor(new java.awt.Color(102, 0, 255));
        buttonBorder4.setColorClick(new java.awt.Color(153, 153, 255));
        buttonBorder4.setColorOver(new java.awt.Color(204, 204, 255));
        buttonBorder4.setRadius(31);
        buttonBorder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(buttonBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
String path="";
    private void buttonBorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder1ActionPerformed
        JFileChooser cf=new JFileChooser();
    cf.setFileSelectionMode(JFileChooser.FILES_ONLY);
    cf.setCurrentDirectory(new java.io.File("/home/fofana/Téléchargements/modele"));
    int result=cf.showOpenDialog(null);
    String imc;
    if(result==JFileChooser.APPROVE_OPTION){
        path=cf.getSelectedFile().getAbsolutePath();
        imc=cf.getSelectedFile().getPath();
        labelImage1.setIcon(new ImageIcon(imc));
    }
    else{
        cf.setVisible(false);
    }
    }//GEN-LAST:event_buttonBorder1ActionPerformed

    private void buttonBorder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder4ActionPerformed
        FrameAdd.setVisible(true);
    }//GEN-LAST:event_buttonBorder4ActionPerformed

    private void buttonBorder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder2ActionPerformed
        ModeleDAO m=new ModeleDAO();
            String nom=textField1.getText();
            String type=jComboBox1.getSelectedItem().toString();
            if(nom.equals("")||path.equals("")){
                new Message().affiche("Données Incomplete",Message.INFO);
            }
            else{
        try {
            m.inserer(nom, path,type);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelModele.class.getName()).log(Level.SEVERE, null, ex);
        }
        FrameAdd.dispose();
        path="";
        textField1.setText("");
        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imageVide.jpg")));
            }
    }//GEN-LAST:event_buttonBorder2ActionPerformed

    private void buttonBorder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder3ActionPerformed
        FrameAdd.dispose();
        path="";
        textField1.setText("");
        labelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imageVide.jpg")));
    }//GEN-LAST:event_buttonBorder3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameAdd;
    private classe_special.ButtonBorder buttonBorder1;
    private classe_special.ButtonBorder buttonBorder2;
    private classe_special.ButtonBorder buttonBorder3;
    private classe_special.ButtonBorder buttonBorder4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private classe_special.LabelImage labelImage1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
}
