/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Article;
import classe.Client;
import classe.Commande;
import classe.Personnel;
import classe_special.Message;
import classe_special.ScrollBar;
import dao.ArticleDAO;
import dao.ClientDAO;
import dao.CommandeDAO;
import dao.PersonnelDAO;
import java.awt.Color;
import java.awt.Point;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import report.ReportDetailCommande;
import report.ReportFacture;

/**
 *
 * @author HP
 */
public class PanelDepot extends javax.swing.JPanel {

    /**
     * Creates new form PanelDepot
     */
    public PanelDepot() {
        initComponents();
        liste_depot();
        listeCarte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameDetail = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomClient = new javax.swing.JLabel();
        contactClient = new javax.swing.JLabel();
        prixCommande = new javax.swing.JLabel();
        tabArticle = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tb_depot = new classe_special.Tableaux();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        carte1 = new classe_special.Carte();
        carte2 = new classe_special.Carte();
        carte3 = new classe_special.Carte();
        btDetail = new classe_special.ButtonBorder();
        btnFini = new classe_special.ButtonBorder();
        btnFacture = new classe_special.ButtonBorder();
        btnRetire = new classe_special.ButtonBorder();
        buttonBorder1 = new classe_special.ButtonBorder();
        buttonBorder2 = new classe_special.ButtonBorder();

        FrameDetail.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FrameDetail.setLocation(new java.awt.Point(333, 111));
        FrameDetail.setSize(new java.awt.Dimension(1025, 631));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nom du Client");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Contact Client");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Prix Commande");

        nomClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        contactClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        prixCommande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactClient, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(prixCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(prixCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Les Articles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabArticle)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameDetailLayout = new javax.swing.GroupLayout(FrameDetail.getContentPane());
        FrameDetail.getContentPane().setLayout(FrameDetailLayout);
        FrameDetailLayout.setHorizontalGroup(
            FrameDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameDetailLayout.setVerticalGroup(
            FrameDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        scroll.setBorder(null);
        scroll.setVerticalScrollBar(new ScrollBar());
        scroll.getVerticalScrollBar().setBackground(Color.BLUE);

        tb_depot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id commande", "Client", "Date de depot", "nbre Article", "Prix", "Delai"
            }
        ));
        tb_depot.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tb_depot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_depotMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_depotMouseReleased(evt);
            }
        });
        scroll.setViewportView(tb_depot);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toutes", "En cours", "Attente de retrait", "Retiré" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Type");

        carte1.setBackground(new java.awt.Color(51, 51, 51));

        carte2.setBackground(new java.awt.Color(255, 102, 102));

        carte3.setBackground(new java.awt.Color(204, 204, 0));

        btDetail.setText("Detail");
        btDetail.setBorderColor(new java.awt.Color(51, 51, 255));
        btDetail.setColorClick(new java.awt.Color(102, 102, 255));
        btDetail.setColorOver(new java.awt.Color(204, 204, 255));
        btDetail.setRadius(33);
        btDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetailActionPerformed(evt);
            }
        });

        btnFini.setText("Commande Fini");
        btnFini.setBorderColor(new java.awt.Color(51, 51, 255));
        btnFini.setColorClick(new java.awt.Color(102, 102, 255));
        btnFini.setColorOver(new java.awt.Color(204, 204, 255));
        btnFini.setRadius(33);
        btnFini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiniActionPerformed(evt);
            }
        });

        btnFacture.setText("Facture");
        btnFacture.setBorderColor(new java.awt.Color(51, 51, 255));
        btnFacture.setColorClick(new java.awt.Color(102, 102, 255));
        btnFacture.setColorOver(new java.awt.Color(204, 204, 255));
        btnFacture.setRadius(33);
        btnFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactureActionPerformed(evt);
            }
        });

        btnRetire.setText("Retiré");
        btnRetire.setBorderColor(new java.awt.Color(51, 51, 255));
        btnRetire.setColorClick(new java.awt.Color(102, 102, 255));
        btnRetire.setColorOver(new java.awt.Color(204, 204, 255));
        btnRetire.setRadius(33);
        btnRetire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetireActionPerformed(evt);
            }
        });

        buttonBorder1.setText("Commande Par jours");
        buttonBorder1.setBorderColor(new java.awt.Color(51, 102, 255));
        buttonBorder1.setColorClick(new java.awt.Color(153, 204, 255));
        buttonBorder1.setColorOver(new java.awt.Color(204, 255, 255));
        buttonBorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder1ActionPerformed(evt);
            }
        });

        buttonBorder2.setText("Données de la commande");
        buttonBorder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorder2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnFini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnRetire, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(buttonBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(carte1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(carte2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(carte3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(buttonBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(buttonBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRetire, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(btnFini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btDetail, btnFacture, btnFini});

    }// </editor-fold>//GEN-END:initComponents

    private void tb_depotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_depotMouseClicked

    }//GEN-LAST:event_tb_depotMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        listeChoix();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetailActionPerformed
       int index = tb_depot.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une commande",Message.ALERT);
        }
        else {
         int id = (int)tb_depot.getValueAt(index,0);
            detail(id);
        }
    }//GEN-LAST:event_btDetailActionPerformed

    private void btnFiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiniActionPerformed
        int index = tb_depot.getSelectedRow();
        if (index==-1){
            new Message().affiche("Veuillez selectionnez une commande",Message.ALERT);
        }
        else {
            int id = (int)tb_depot.getValueAt(index,0);
            CommandeDAO cdao = new CommandeDAO();
            Commande cmd=cdao.recherche(id);
            if(cmd.isEtat()==true){
                new Message().affiche("La commande est deja enregistrer comme fini",Message.INFO);
            }
            else{
            cdao.commandefini(id);
            vider();
            listeChoix();
            listeCarte();
            }
        }
    }//GEN-LAST:event_btnFiniActionPerformed

    private void btnFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactureActionPerformed
        int index = tb_depot.getSelectedRow();
        if(index==-1){
          new Message().affiche("Veuillez selectionnez une commande",Message.ALERT);
        }
        else{
        int id = (int)tb_depot.getValueAt(index,0);
        new ReportFacture().affiche(id);
        }
    }//GEN-LAST:event_btnFactureActionPerformed

    private void tb_depotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_depotMouseReleased
           
    }//GEN-LAST:event_tb_depotMouseReleased

    private void btnRetireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetireActionPerformed
      int index = tb_depot.getSelectedRow();
        if(index==-1){
          new Message().affiche("Veuillez selectionnez une commande",Message.ALERT);
        }
        else{
        int id = (int)tb_depot.getValueAt(index,0);
            CommandeDAO cdao = new CommandeDAO();
            Commande cmd=cdao.recherche(id);
            if(cmd.getRetrait()!=null){
                new Message().affiche("La commande a deja été retiré",Message.INFO);
            }
            else{
            cdao.insererRetrait(id);
            vider();
            listeChoix();
            listeCarte();
            }
        }
    }//GEN-LAST:event_btnRetireActionPerformed

    private void buttonBorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder1ActionPerformed
       new FrameCommande().setVisible(true);
    }//GEN-LAST:event_buttonBorder1ActionPerformed

    private void buttonBorder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorder2ActionPerformed
        // TODO add your handling code here:
        new FrameChart().dessiner(encours, fini, retiré);
    }//GEN-LAST:event_buttonBorder2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameDetail;
    private classe_special.ButtonBorder btDetail;
    private classe_special.ButtonBorder btnFacture;
    private classe_special.ButtonBorder btnFini;
    private classe_special.ButtonBorder btnRetire;
    private classe_special.ButtonBorder buttonBorder1;
    private classe_special.ButtonBorder buttonBorder2;
    private classe_special.Carte carte1;
    private classe_special.Carte carte2;
    private classe_special.Carte carte3;
    private javax.swing.JLabel contactClient;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nomClient;
    private javax.swing.JLabel prixCommande;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTabbedPane tabArticle;
    private classe_special.Tableaux tb_depot;
    // End of variables declaration//GEN-END:variables
private void liste_depot() {
        CommandeDAO pdao = new CommandeDAO();
        List<Commande> cmd = pdao.liste();
        
        for (int i = 0; i < cmd.size(); i++) {
            ClientDAO cdao = new ClientDAO();
            Client clt=cdao.recherche(cmd.get(i).getId_client());
            int idclient=clt.getId_client();
            String nomclt=clt.getNom();
            ((DefaultTableModel) tb_depot.getModel()).addRow(new Object[]{
                  cmd.get(i).getId_commande(),
                  idclient+" "+nomclt,
                  cmd.get(i).getDepot(),
                  cmd.get(i).getNbreArticle(),
                  cmd.get(i).getPrixTotal()+" FCFA",
                  cmd.get(i).getDelai()
            });
    }
}

public void listeChoix(){
    String type=jComboBox1.getSelectedItem().toString();
        CommandeDAO pdao = new CommandeDAO();
        List<Commande> cmd = pdao.liste();
        if(type.equals("Toutes")){
            vider();liste_depot();
        }
        else if(type.equals("En cours")){
            vider();
             for (int i = 0; i < cmd.size(); i++) {
            ClientDAO cdao = new ClientDAO();
            Client clt=cdao.recherche(cmd.get(i).getId_client());
            int idclient=clt.getId_client();
            String nomclt=clt.getNom();
            if((cmd.get(i).isEtat()==false)){
            ((DefaultTableModel) tb_depot.getModel()).addRow(new Object[]{
                  cmd.get(i).getId_commande(),
                  idclient+" "+nomclt,
                  cmd.get(i).getDepot(),
                  cmd.get(i).getNbreArticle(),
                  cmd.get(i).getPrixTotal(),
                  cmd.get(i).getDelai()
            });
            
           }  
          }
        }
        else if(type.equals("Attente de retrait")){
            vider();
             for (int i = 0; i < cmd.size(); i++) {
            ClientDAO cdao = new ClientDAO();
            Client clt=cdao.recherche(cmd.get(i).getId_client());
            int idclient=clt.getId_client();
            String nomclt=clt.getNom();
            if((cmd.get(i).isEtat()==true)&&(cmd.get(i).getRetrait()==null)){
            ((DefaultTableModel) tb_depot.getModel()).addRow(new Object[]{
                  cmd.get(i).getId_commande(),
                  idclient+" "+nomclt,
                  cmd.get(i).getDepot(),
                  cmd.get(i).getNbreArticle(),
                  cmd.get(i).getPrixTotal(),
                  cmd.get(i).getDelai()
            });
            
           }  
          }
        }
        else if(type.equals("Retiré")){
            vider();
             for (int i = 0; i < cmd.size(); i++) {
            ClientDAO cdao = new ClientDAO();
            Client clt=cdao.recherche(cmd.get(i).getId_client());
            int idclient=clt.getId_client();
            String nomclt=clt.getNom();
            if((cmd.get(i).getRetrait()!=null)){
            ((DefaultTableModel) tb_depot.getModel()).addRow(new Object[]{
                  cmd.get(i).getId_commande(),
                  idclient+" "+nomclt,
                  cmd.get(i).getDepot(),
                  cmd.get(i).getNbreArticle(),
                  cmd.get(i).getPrixTotal(),
                  cmd.get(i).getDelai()
            });
            
           }  
          }
        }
}
public void vider() {
        DefaultTableModel model = (DefaultTableModel) tb_depot.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
        
    }

int encours= 0; int fini=0; int retiré=0;
private void listeCarte(){
    
    CommandeDAO cdao = new CommandeDAO();
    List<Commande> cmd = cdao.liste();
    carte1.setData("Depot total", ""+cmd.size());
    
    for (int i = 0; i < cmd.size(); i++) {
        if(cmd.get(i).isEtat()==false){
            encours++;
        }
        else if(cmd.get(i).getRetrait()==null){
            fini++;
        }
        else{
            retiré++;
        }
        
    }
    int c=fini+retiré;
    carte2.setData("Commande en cours", ""+encours);
    carte3.setData("Commande fini", ""+c);
  }
public void acces(){
    btnRetire.setVisible(false);
}
public void accesSecretaire(){
    btnFini.setVisible(false);
}
private void detail(int idcommande){
    
    CommandeDAO cmd=new CommandeDAO();
    Commande c=cmd.recherche(idcommande);
    
    ClientDAO cdao=new ClientDAO();
    Client clt=cdao.recherche(c.getId_client());
    
    ArticleDAO ardao=new ArticleDAO();
    List<Article> la=ardao.listeArticle(idcommande);
    nomClient.setText(""+clt.getNom()); contactClient.setText(clt.getContact());
    prixCommande.setText(c.getPrixTotal()+"");
    tabArticle.removeAll();
    for (int i = 0; i < la.size(); i++){
        tabArticle.addTab("Article N°"+(i+1), new PanelArticle(la.get(i)));
    }
    FrameDetail.setLocationRelativeTo(null);
    FrameDetail.setVisible(true);
}

}
