/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Personnel;
import classe.Utilisateur;
import classe_special.Confirm;
import classe_special.Message;
import classe_special.ScrollBar;
import dao.PersonnelDAO;
import dao.UtilisateurDAO;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import report.ReportUtilisateur;

/**
 *
 * @author HP
 */
public class PanelUtilisateur extends javax.swing.JPanel {
boolean modifier;
    
    public PanelUtilisateur() {
        initComponents();
        liste_utilisateur();
        listeCarte();
        combo_personnel();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameEnregistrer = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEnregistrer = new javax.swing.JButton();
        btnEnAnnuler = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        menu = new javax.swing.JPopupMenu();
        editer = new javax.swing.JMenuItem();
        supprimer = new javax.swing.JMenuItem();
        scroll = new javax.swing.JScrollPane();
        tb_utilisateur = new classe_special.Tableaux();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btAjouter = new javax.swing.JLabel();
        btSupprimer = new javax.swing.JLabel();
        btModifier = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        carte1 = new classe_special.Carte();
        carte2 = new classe_special.Carte();
        carte3 = new classe_special.Carte();

        FrameEnregistrer.setLocation(new java.awt.Point(465, 165));
        FrameEnregistrer.setUndecorated(true);
        FrameEnregistrer.setResizable(false);
        FrameEnregistrer.setSize(new java.awt.Dimension(488, 355));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Login");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Profil");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Employé");

        btnEnregistrer.setBackground(new java.awt.Color(0, 102, 255));
        btnEnregistrer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEnAnnuler.setBackground(new java.awt.Color(255, 0, 51));
        btnEnAnnuler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnEnAnnuler.setText("Annuler");
        btnEnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnAnnulerActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Couturie", "Secretaire" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnEnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout FrameEnregistrerLayout = new javax.swing.GroupLayout(FrameEnregistrer.getContentPane());
        FrameEnregistrer.getContentPane().setLayout(FrameEnregistrerLayout);
        FrameEnregistrerLayout.setHorizontalGroup(
            FrameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameEnregistrerLayout.setVerticalGroup(
            FrameEnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                menuPopupMenuWillBecomeVisible(evt);
            }
        });

        editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        editer.setText("Modifier");
        editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerActionPerformed(evt);
            }
        });
        menu.add(editer);

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        menu.add(supprimer);

        setBackground(new java.awt.Color(249, 249, 252));

        scroll.setBorder(null);
        scroll.setVerticalScrollBar(new ScrollBar());
        scroll.getVerticalScrollBar().setBackground(Color.BLUE);

        tb_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idu", "Login", "Password", "Profil", "Employer"
            }
        ));
        tb_utilisateur.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tb_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_utilisateurMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_utilisateurMouseReleased(evt);
            }
        });
        scroll.setViewportView(tb_utilisateur);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("LISTE DES UTILISATEURS  ");

        btAjouter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ajouter.png"))); // NOI18N
        btAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAjouterMouseClicked(evt);
            }
        });

        btSupprimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        btSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSupprimerMouseClicked(evt);
            }
        });

        btModifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        btModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btModifierMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imprimante.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSupprimer)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btAjouter)
                                .addComponent(btModifier))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        carte2.setBackground(new java.awt.Color(102, 0, 0));

        carte3.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        UtilisateurDAO udao = new UtilisateurDAO();
        String login = jTextField2.getText();
        String password =jFormattedTextField1.getText();
        String profil = jComboBox1.getSelectedItem().toString();
        int indexfin=jComboBox2.getSelectedItem().toString().indexOf(" ");
        String idp=jComboBox2.getSelectedItem().toString().substring(0, indexfin);
        if (login.equals("") || password.equals("")) {
            new Message().affiche("Veuillez renseigner tous les champs ",Message.ALERT);
        } 
        else if(modifier==false) {
            Utilisateur ut = new Utilisateur(login, password,profil,Integer.parseInt(idp));
            udao.inserer(ut);
            vider();
            liste_utilisateur();
            FrameEnregistrer.setVisible(false);
        }
        else if(modifier==true) {
            int index = tb_utilisateur.getSelectedRow();
             int id = (int)tb_utilisateur.getValueAt(index,0);
            Utilisateur ut = new Utilisateur(login, password,profil,Integer.parseInt(idp));
            udao.modifier(ut, id);
            vider();
            liste_utilisateur();
            FrameEnregistrer.setVisible(false);
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnEnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnAnnulerActionPerformed
           FrameEnregistrer.setVisible(false);
           vider();
            liste_utilisateur();
    }//GEN-LAST:event_btnEnAnnulerActionPerformed

    private void tb_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_utilisateurMouseClicked
        int index = tb_utilisateur.getSelectedRow();
        if (index!=-1){
          int id = (int)tb_utilisateur.getValueAt(index,0);
            UtilisateurDAO udao = new UtilisateurDAO();
            Utilisateur ut = udao.recherche(id);
            jTextField2.setText(ut.getLogin());
            jFormattedTextField1.setText(ut.getPassword());
            jComboBox1.setSelectedItem(ut.getProfil());
            PersonnelDAO pdao = new PersonnelDAO();
            Personnel personnel=pdao.recherche(ut.getIdp());
            jComboBox2.setSelectedItem(personnel.getIdp()+" "+personnel.getNom()+" "+personnel.getPrenom());
        }
    }//GEN-LAST:event_tb_utilisateurMouseClicked

    private void btAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAjouterMouseClicked
        FrameEnregistrer.setVisible(true);
        modifier=false;
        jTextField2.setText("");
        jComboBox2.setSelectedItem(ABORT);
        jFormattedTextField1.setText("");
        jComboBox1.setSelectedItem(ABORT);
    }//GEN-LAST:event_btAjouterMouseClicked

    private void btModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btModifierMouseClicked
        int ind = tb_utilisateur.getSelectedRow();
        if (ind==-1){
            new Message().affiche("Veuillez selectionnez un utilisateur",Message.INFO);
        }
        else {
        FrameEnregistrer.setVisible(true);
        modifier=true;
        }
    }//GEN-LAST:event_btModifierMouseClicked

    private void btSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSupprimerMouseClicked
        int index = tb_utilisateur.getSelectedRow();
        if (index==-1){
           new Message().affiche("Veuillez selectionnez un utilisateur",Message.INFO);
        }
        else {
           new Confirm().affiche("Supprimer?","Etes vous sur de vouloir Supprimer Cet Utilisateur!!!", new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent ae) {
        int id = (int)tb_utilisateur.getValueAt(index,0);
        UtilisateurDAO udao = new UtilisateurDAO();
        udao.supprimer(id);
        vider();
        liste_utilisateur();
               }
           });
        }
    }//GEN-LAST:event_btSupprimerMouseClicked

    private void tb_utilisateurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_utilisateurMouseReleased
       if(SwingUtilities.isRightMouseButton(evt)){
            menu.show(this,this.getMousePosition().x,this.getMousePosition().y);
        }
    }//GEN-LAST:event_tb_utilisateurMouseReleased

    private void menuPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_menuPopupMenuWillBecomeVisible
       
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                int index=tb_utilisateur.rowAtPoint(SwingUtilities.convertPoint(menu,new Point(1, 1), tb_utilisateur));
                if(index > -1){
                tb_utilisateur.setRowSelectionInterval(index, index);
                int id = (int)tb_utilisateur.getValueAt(index,0);
            UtilisateurDAO udao = new UtilisateurDAO();
            Utilisateur ut = udao.recherche(id);
            jTextField2.setText(ut.getLogin());
            jFormattedTextField1.setText(ut.getPassword());
            jComboBox1.setSelectedItem(ut.getProfil());
            PersonnelDAO pdao = new PersonnelDAO();
            Personnel personnel=pdao.recherche(ut.getIdp());
            jComboBox2.setSelectedItem(personnel.getIdp()+" "+personnel.getNom()+" "+personnel.getPrenom());
        }
            }
        });
       
    }//GEN-LAST:event_menuPopupMenuWillBecomeVisible

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
int index = tb_utilisateur.getSelectedRow();
        new Confirm().affiche("Supprimer","Etes vous sur de vouloir Supprimer Cet utilisateur!!!", new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent ae) {
        int id = (int)tb_utilisateur.getValueAt(index,0);
        UtilisateurDAO udao = new UtilisateurDAO();
        udao.supprimer(id);
        vider();
        liste_utilisateur();
               }
           });
    }//GEN-LAST:event_supprimerActionPerformed

    private void editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerActionPerformed
        FrameEnregistrer.setVisible(true);
        modifier=true;
    }//GEN-LAST:event_editerActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new ReportUtilisateur().afficher();
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameEnregistrer;
    private javax.swing.JLabel btAjouter;
    private javax.swing.JLabel btModifier;
    private javax.swing.JLabel btSupprimer;
    private javax.swing.JButton btnEnAnnuler;
    private javax.swing.JButton btnEnregistrer;
    private classe_special.Carte carte1;
    private classe_special.Carte carte2;
    private classe_special.Carte carte3;
    private javax.swing.JMenuItem editer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JMenuItem supprimer;
    private classe_special.Tableaux tb_utilisateur;
    // End of variables declaration//GEN-END:variables
 private void liste_utilisateur() {
        UtilisateurDAO udao = new UtilisateurDAO();
        List<Utilisateur> utilisateur = udao.liste();
        
        for (int i = 0; i < utilisateur.size(); i++) {
            PersonnelDAO pdao = new PersonnelDAO();
            Personnel personnel=pdao.recherche(utilisateur.get(i).getIdp());
            String employe=personnel.getNom()+" "+personnel.getPrenom();
            ((DefaultTableModel) tb_utilisateur.getModel()).addRow(new Object[]{
                utilisateur.get(i).getIdu(),
                utilisateur.get(i).getLogin(),
                utilisateur.get(i).getPassword(),
                utilisateur.get(i).getProfil(),
                employe
            });
        }

    }

public void vider() {
        jTextField2.setText("");
        jComboBox2.setSelectedItem(ABORT);
        jFormattedTextField1.setText("");
        jComboBox1.setSelectedItem(ABORT);
        DefaultTableModel model = (DefaultTableModel) tb_utilisateur.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
private void combo_personnel() {
        PersonnelDAO edao = new PersonnelDAO();
        List<Personnel> personnel = edao.liste();
        for (int i = 0; i < personnel.size(); i++) {
           jComboBox2.addItem(personnel.get(i).getIdp()+" "+personnel.get(i).getNom()+" "+personnel.get(i).getPrenom());
        }

    }
private void listeCarte(){
    UtilisateurDAO udao = new UtilisateurDAO();
        List<Utilisateur> utilisateur = udao.liste();
        
     int nbreAdmin=0; int nbreCouturie=0; int nbreSecretaire=0;
     for (int i = 0; i < utilisateur.size(); i++) {
            if(utilisateur.get(i).getProfil().equals("Administrateur"))
                nbreAdmin++;
            else if(utilisateur.get(i).getProfil().equals("Couturie"))
                nbreCouturie++;
            else if(utilisateur.get(i).getProfil().equals("Secretaire"))
                nbreSecretaire++;
     }
     carte1.setData("Administrateur", ""+nbreAdmin);
     carte2.setData("Couturie", ""+nbreCouturie);
     carte3.setData("Receptioniste", ""+nbreSecretaire);
  }

}
